### ISSUE TITLE
Runtime Error DailyBackup.py

### ISSUE THREAD

**Issue by jangt15** [extremenetworks/ExtremeScripting#111]
Hi,

I receive always the following Error when I run the Script DailyBackup.py on my Extreme Switch. 

 load script backup_config.py 
%% Unrecognized command:  ""
%% Invalid input detected.
Traceback (most recent call last):
  File "/usr/local/cfg/backup_config.py", line 117, in <module>
    if upmConfig() == None:
  File "/usr/local/cfg/backup_config.py", line 112, in upmConfig
    exosCmd(cmd)
  File "/usr/local/cfg/backup_config.py", line 42, in exosCmd
    result = exsh.clicmd(cmd, True)
RuntimeError

I run it with Firmware Version 22.4.1.4

Do you have any idea why?

**Comment by stewilliams-extr** [comment]
The issue was fixed with the below commit. 

https://github.com/extremenetworks/ExtremeScripting/commit/3ffaeb1b749dd1aea17a1f3a755d2a7ee744d780
