### ISSUE TITLE
Change Policy file (.POL)

### ISSUE THREAD

**Issue by natchamonk** [extremenetworks/ExtremeScripting#138]
Hi Sir,

Could you please help create API to change POLICY file(.POL)?

**Comment by ZdenekPala** [comment]
Please elaborate more on the request. There are API calls available today to modify the Policy definition in XIQ-SE.

**Comment by natchamonk** [comment]
Hi Pala,

Customer has his owns application and would like to use his application to change the acl on the switch without XIQ-SE.

Can you share the script? If it cannot, Can you share the script that run on switch to edit such as add, remove and change the line on .pol file?

**Comment by ZdenekPala** [comment]
I see. I mixed POL file (on the switch) and PMD file (policy definition in XMC/XIQ-SE).
Thank you for the clarification.

**Comment by ZdenekPala** [comment]
closing because of no reaction for three months
