### ISSUE TITLE
Onboard Mgmt CLIP & VLAN process order

### ISSUE THREAD

**Issue by samconder** [extremenetworks/ExtremeScripting#143]
In both the Onboard Mgmt CLIP and Onboard Mgmt VLAN workflows, the rename function is being executed after the device gets deleted and re-added to XiQ-SE, therefore it is added with the "old" device name. I moved the "Change the System Name now" block up to just after the final "Enter Config context" and the now the device is re-added with the "new" name.

**Comment by lgastevens** [comment]
Hi, thanks for the feedback.
Maybe the device gets re-added with the old name initially, however a re-discovery of the device should yield the new name.
My approach was to make sure the IP address change is a success, before going in to make other config changes (the sys-name). That way, if the workflow fails, the device is still in it's original and expected state.
What I can do is automatically trigger a re-discovery of the device at the very end. I think that is the best approach.

**Comment by samconder** [comment]
The net result would be the same, the device migrated to mgmt and the correct sys-name reflected in Site Engine without manual intervention. Sounds reasonable.  Thanks.

**Comment by lgastevens** [comment]
Hi, I have updated both the Onboard Mgmt CLIP and Onboard Mgmt VLAN workflows (v7 & v29 respectively). They now trigger an XIQ-SE rediscovery on completion. I have tested both and they work well on my side. Another change added, from a different ask, is to allow them to index the MAC address as an alternative to Serial Number in the CSV file.

**Comment by ZdenekPala** [comment]
both the Onboard Mgmt CLIP and Onboard Mgmt VLAN workflows (v7 & v29 respectively) are updated. They now trigger an XIQ-SE rediscovery on completion. I have tested both and they work well on my side. Another change added, from a different ask, is to allow them to index the MAC address as an alternative to Serial Number in the CSV file.
