### ISSUE TITLE
No Primary Engine IP found in NAC Engine Group name Default

### ISSUE THREAD

**Issue by rstewart8520** [extremenetworks/ExtremeScripting#147]
I guess it is not really an Issue it is by design currently.
I have found times that we will not have a NAC for port auth.  i would like to have the workflow bypass the NAC / Radius if that input value is marked as disabled.

i had to install a NAC that will not be licensed and or used just to have the workflow work

**Comment by ZdenekPala** [comment]
Hi rstewart8520,
What workflow are you referring to?

Thank you

**Comment by ZdenekPala** [comment]
Closing because of no response
