### ISSUE TITLE
Onboard Mgmt VLAN from OOB

### ISSUE THREAD

**Issue by faekz0r** [extremenetworks/ExtremeScripting#148]
I tried using the "Onboard Mgmt VLAN" workflow, after ZTP+ process through the OOB. It will fail for several reasons. Starting with the error:
`Error: Mgmt convert - an ip address is mandatory to convert the interface`
after the `convert vlan ...` command in the script.
Since we do not have an ip address assigned for the mgmt vlan.
And even if we assign one, the next error will be, that the mgmt vlan interface is disabled. Which is normal behavior in such a deployment process.

**Comment by lgastevens** [comment]
The workflow was designed assuming the switch would initially get a DHCP IP address inband, on the default mgmt VLAN 4048.
It was not designed for the case where the switch would get initial DHCP IP on the OOB port.
Campus deployments will always use inband.
Do you see value in supporting the OOB case ? Is Data Center your use case ?
I would need to spend cycles to make it work from an initial OOB IP

**Comment by faekz0r** [comment]
> Do you see value in supporting the OOB case ?
No, not really. My main aim was to just inform.

But I do have a big issue with the workflow nonetheless - we can not use it in a ZTP process without the workflow braking without any "manual" involvement in our part.

If we connect the VOSS switch to an uplink, SE will configure an IP on its onboarding vlan 4048. The port will be an untagged one. If the workflow now configures a new IP on a new subnet and on a new vlan, there will be no L2 connection to this vlan and the workflow brakes, because we can no longer reach the switch, unless we manually configure and connect another port beforehand to a tagged vlan for this new mgmt network, before we run the workflow.

Maybe I am just missing something, but so far that's my biggest gripe with the whole process.

If we could use the same physical uplink we used for ZTP (untagged vlan 4048), to change to a new tagged network, it would be great, but there seems to be no step that would do that.

I tried Port Mappings (from Port templates) as well to tackle this issue, but at least for Universal Platform Fabric switches it's not working at all.

**Comment by lgastevens** [comment]
The intended use is for Fabric to the edge. The switch uplink(s) will be fabric (NNI) uplink(s), which will have configured themselves automatically by auto-sense, provided that another VSP/Fabric Engine is at the other side of the link(s). There are no VLANs on fabric links. The I-SID is sufficient to attach the new mgmt VLAN IP into the desired fabric segment.
It sounds like your use case is more of a legacy deployment, into a traditional non-fabric core switch, hence you need to worry about having the VLANs tagged on your uplink.. so I don't think this workflow is for you, or you would need to modify the workflow to take care of the extra logic to handle the uplink VLAN config changes as well.
Why are you using VOSS ? If your switch is Universal hardware, you can use EXOS instead, and XIQ-SE can natively allow you to onboard the EXOS switch into a different VLAN from the one it got DHCP from, and it can handle the VLAN config on uplinks as well.

**Comment by faekz0r** [comment]
> The intended use is for Fabric to the edge. The switch uplink(s) will be fabric (NNI) uplink(s), which will have configured themselves automatically by auto-sense, provided that another VSP/Fabric Engine is at the other side of the link(s). There are no VLANs on fabric links. The I-SID is sufficient to attach the new mgmt VLAN IP into the desired fabric segment. It sounds like your use case is more of a legacy deployment, into a traditional non-fabric core switch, hence you need to worry about having the VLANs tagged on your uplink.. so I don't think this workflow is for you, or you would need to modify the workflow to take care of the extra logic to handle the uplink VLAN config changes as well. Why are you using VOSS ? If your switch is Universal hardware, you can use EXOS instead, and XIQ-SE can natively allow you to onboard the EXOS switch into a different VLAN from the one it got DHCP from, and it can handle the VLAN config on uplinks as well.

Our use case at this moment has actually been only a lab. So I started by trying to configure the fabric core in as automated way as possible. What you have described, has probably been the missing link. I can definitely create a setup where we configure the Fabric "core" manually with all the needed vlans/i-sids and then get the edge deployed fully automatically with the help of your workflow. 

Thank you very much! Will try to build it in the coming days.

**Comment by faekz0r** [comment]
> > The intended use is for Fabric to the edge. The switch uplink(s) will be fabric (NNI) uplink(s), which will have configured themselves automatically by auto-sense, provided that another VSP/Fabric Engine is at the other side of the link(s). There are no VLANs on fabric links. The I-SID is sufficient to attach the new mgmt VLAN IP into the desired fabric segment. It sounds like your use case is more of a legacy deployment, into a traditional non-fabric core switch, hence you need to worry about having the VLANs tagged on your uplink.. so I don't think this workflow is for you, or you would need to modify the workflow to take care of the extra logic to handle the uplink VLAN config changes as well. Why are you using VOSS ? If your switch is Universal hardware, you can use EXOS instead, and XIQ-SE can natively allow you to onboard the EXOS switch into a different VLAN from the one it got DHCP from, and it can handle the VLAN config on uplinks as well.
> 
> Our use case at this moment has actually been only a lab. So I started by trying to configure the fabric core in as automated way as possible. What you have described, has probably been the missing link. I can definitely create a setup where we configure the Fabric "core" manually with all the needed vlans/i-sids and then get the edge deployed fully automatically with the help of your workflow.
> 
> Thank you very much! Will try to build it in the coming days.

The described solution worked without any problems. Thank you! <3
