### ISSUE TITLE
Password Prompting 

### ISSUE THREAD

**Issue by chthompson-extr** [extremenetworks/ExtremeScripting#150]
This script will not work with cli password prompting on and that issue should be documented:

 ExtremeCore.4 # configure cli password prompting-only on
* ExtremeCore.5 # run script snmpassist.py
Would you like to (D)elete or (C)onfigure SNMPv3? c
Please enter your SNMPv3 User name: test
Please enter your SNMPv3 User password (8 to 49 char): testtest
Please enter your SNMPv3 privacy password (8 to 49 char): testtest
Please enter your authentication type (SHA/MD5): md5
Please enter your encryption type (3DES, AES, DES, HEX): des

Traceback (most recent call last):
  File "/usr/local/cfg/snmpassist.py", line 204, in <module>
    main()
  File "/usr/local/cfg/snmpassist.py", line 119, in main
    (snmpuser, authtype, authpw, privpw, privtype))

**Comment by ZdenekPala** [comment]
please provide some context. what script?
