### ISSUE TITLE
XIQ-SE always sees differences in VLAN configuration imported using "Import VLANs and Services" workflow

### ISSUE THREAD

**Issue by TheNetworkIsDown** [extremenetworks/ExtremeScripting#154]
XIQ-SE "Enforce Preview" always detected differences on all the VLANs added using this workflow.

The strange thing was:
1) After hitting Enforce once, all VLANs returned to green (no difference anymore).
2) Exiting the dialog and going back in, all VLANs were shown in red again (differences).

We found out this is probably due to igmpQuerier being set to "0.0.0.0". We manually changed all the VLANs and set igmpQuerier to the empty string "". The problem was gone after that.

I'm not sure what would fix this, maybe setting igmpQuerier:null or igmpQuerier:"" instead of igmpQuerier:"0.0.0.0".

XIQ-SE 22.9.12.14 
FabricEngine 8.8.1.0

**Comment by mnikulski** [comment]
just to make sure.
You referring to the workflows "Import VLANs and Services from VSP" version 15?
I inspected the code and can not find any IGMP settings.
