### ISSUE TITLE
Unable to run git_download.py

### ISSUE THREAD

**Issue by ShadowLinks** [extremenetworks/ExtremeScripting#156]
ExtremeXOS version 30.7.2.1 30.7.2.1-patch1-71
Model: X460-G2

used tftp to get the file onto the switch and ran the command for dns
configure dns-client add name-server [internal dns ip] vr VR-Default 

Slot-1 Tech-Test-x460.55 # run script git_download.py
DNS is misconfigured or no internet access was found on VR-Default or VR-Mgmt

Configure DNS with the command 'configure dns-client add name-server <DNS IP> vr <vr name>'
Traceback (most recent call last):
  File "/usr/local/cfg/git_download.py", line 130, in <module>
    main()
  File "/usr/local/cfg/git_download.py", line 126, in main
    vr_change('0')
  File "/usr/local/cfg/git_download.py", line 7, in vr_change
    f = open("/proc/self/ns_id", "w")
IOError: [Errno 2] No such file or directory: '/proc/self/ns_id'
Slot-1 Tech-Test-x460.56 #

Tried doing this after wiping a switch and doing our basic configuration on it 
-name
-clear off default vlan ports
-create our vlans and add to uplink ports including our switches-network vlan with the switch IP
-enable ip forwarding on the switch vlan
-added default route
-using the configure dns command from above

DNS and internet does appear to be working as i can ping websites.

**Comment by stewilliams-extr** [comment]
As of right now this Script will only work with versions under 22.7 and older.  This is because of the way we originally changed VRs using the "/proc/self/ns_id" file is no longer an option.

**Comment by ZdenekPala** [comment]
As of right now this Script will only work with versions under 22.7 and older. This is because of the way we originally changed VRs using the "/proc/self/ns_id" file is no longer an option.
