### ISSUE TITLE
Gather Show Support failed

### ISSUE THREAD

**Issue by mnikulski** [extremenetworks/ExtremeScripting#157]
Dear experts,

using VOSS 8.8 or newer the attached e-mail file contain a file with the content
"Error: cli session exceeded buffer capacity: 557039Error: cli session exceeded buffer capacity: 557039"

Please consider to use as well "show fulltech file <name>".

I got as well a information form partner that EXOS with large config also failing. But here I don't have the detail error message.

Thanks

**Comment by stewilliams-extr** [comment]
Could you please report these to the Virtual_VOSS and Virtual_EXOS repo.
