### ISSUE TITLE
mlag_config_check.py ISC Vlan name size 

### ISSUE THREAD

**Issue by stewilliams-extr** [extremenetworks/ExtremeScripting#16]
If ISC VLAN is over 22 character the script will fail at line line 14.  This is because show mlag peer command output bumps into the Virtual Router part of the output.

https://github.com/extremenetworks/ExtremeScripting/tree/master/EXOS/Python/mlag_config_check

**Comment by btclay** [comment]
Just fixed this in pull request #17

**Comment by stewilliams-extr** [comment]
Great fix
