### ISSUE TITLE
Fabric_Cluster_Create.xml errors out on Universal Platform Fabric Engine

### ISSUE THREAD

**Issue by Maranoj** [extremenetworks/ExtremeScripting#163]
Line 260 doesn't allow the script to run on Universal Platform Fabric Engine, it will error. I was able to get the script to run successfully by changing line 260 to if family != "VSP Series" and family != "Universal Platform Fabric Engine":

**Comment by ZdenekPala** [comment]
adjusted these two lines:
    if family != "VSP Series" and family != "Universal Platform Fabric Engine" and family!= "Universal Platform VOSS":
        raise RuntimeError('Error: This script needs to be executed on a switch running VOSS/Fabric Engine')

published new version.

**Comment by ZdenekPala** [comment]
Thank you @Maranoj!
