### ISSUE TITLE
Onboard_Mgmt_VLAN-23.11.10.41v66.xwf unable to run follow on workflow

### ISSUE THREAD

**Issue by jtrott** [extremenetworks/ExtremeScripting#184]
We are trying to use the above workflow as part of our ZTP+ to onboard new switches - the workflow executes fine as long as there isn't a follow on workflow configured as one of the inputs.

As soon as you specify a follow on workflow you get the following (sanitised) output:

Script Name: Onboard Mgmt VLAN_Move_to_VLAN_mgmt_IP
Date and Time: 2024-01-15T16:26:58.108
XIQ-SE User: NetSight Server
XIQ-SE User Domain: 
IP: 1.4.8.11
Workflow version 66 on XIQ-SE/XMC version 23.11.11.9
Activity: MoveToVlanMgmtIp

Input Data:
 - Current Switch IP = 1.4.8.11
 - Selected Switch Serial Number = XXXXXXXXXXXXXXX
 - Selected Switch MAC Address = XX:XX:XX:XX:XX:XX
 - Input CSV file = /root/taskinput/switchdata.csv
 - Key to CSV data = Serial Number
 - Mgmt VLAN id = 1100
 - Mgmt VLAN I-SID = 13001100
 - Mgmt VLAN IP = 1.9.6.132
 - Mgmt VLAN Mask = 255.255.255.0
 - Mgmt VLAN Default Gateway = 1.9.6.1
 - System Name to configure = SWITCH-NAME
 - Auto-sense ISIS Auth key = 
 - XIQ-SE Site to re-add device to = /World
 - Workflow to execute against new VLAN IP after completion = /Workflows/Onboard VSP
 - Selected VSP software version = 9.0.0.0
 - Required Minimum software version = 8.5.0.0
 - VSP switch has required software version = 1
 - Timeout in trying to ping the newly configured mgmt IP = 20 secs
 - Delay time before re-adding device to XIQ-SE = 20 secs
 - Timeout in checking if device was re-added to XIQ-SE = 100 secs
 - Delay time before trying to re-connect to device after re-adding it to XIQ-SE = 10 secs
 - Mgmt convert rollback timer to use = 240 secs
 - Aggressively kill other CLI sessions if unable to save config = 0
 - Do not fail workflow if final save config of switch fails = 0
 - Additional CLI commands:
clock time-zone Australia Sydney
ip dhcp-snooping enable

Traceback (most recent call last):
  File "<string>", line 1538, in <module>
  File "<string>", line 1229, in main
  File "<string>", line 1065, in getWorkflowId
ValueError: too many values to unpack

Traceback (most recent call last):
  File "<string>", line 1538, in <module>
  File "<string>", line 1229, in main
  File "<string>", line 1065, in getWorkflowId
ValueError: too many values to unpack

**Comment by lgastevens** [comment]
Hi
The problem is this input:
`Workflow to execute against new VLAN IP after completion = /Workflows/Onboard VSP`
The workflow is expecting `Workflows/Onboard VSP`
without the leading slash.
I've updated the workflows to give a more understandable error message.
The new version of the workflow will be posted later today.
Best regards
Ludovico Stevens

**Comment by jtrott** [comment]
Hi.

Unfortunately that doesn't resolve the issue. Here is the latest output:

Script Name: Onboard Mgmt VLAN_Move_to_VLAN_mgmt_IP
Date and Time: 2024-01-19T12:11:02.861
XIQ-SE User: NetSight Server
XIQ-SE User Domain: 
IP: 1.4.4.9
Workflow version 66 on XIQ-SE/XMC version 23.11.11.9
Activity: MoveToVlanMgmtIp

Input Data:
 - Current Switch IP = 1.4.4.9
 - Selected Switch Serial Number = Serial-Number
 - Selected Switch MAC Address = XX:XX:XX:XX:XX:XX
 - Input CSV file = /root/taskinput/switchdata.csv
 - Key to CSV data = Serial Number
 - Mgmt VLAN id = 1100
 - Mgmt VLAN I-SID = 13001100
 - Mgmt VLAN IP = 1.1.9.146
 - Mgmt VLAN Mask = 255.255.255.0
 - Mgmt VLAN Default Gateway = 1.1.9.1
 - System Name to configure = SWITCH-NAME
 - Auto-sense ISIS Auth key = 
 - XIQ-SE Site to re-add device to = /World/Switches
 - Workflow to execute against new VLAN IP after completion = Workflows/Onboard VSP
 - Selected VSP software version = 9.0.0.0
 - Required Minimum software version = 8.5.0.0
 - VSP switch has required software version = 1
 - Timeout in trying to ping the newly configured mgmt IP = 20 secs
 - Delay time before re-adding device to XIQ-SE = 20 secs
 - Timeout in checking if device was re-added to XIQ-SE = 100 secs
 - Delay time before trying to re-connect to device after re-adding it to XIQ-SE = 10 secs
 - Mgmt convert rollback timer to use = 240 secs
 - Aggressively kill other CLI sessions if unable to save config = 0
 - Do not fail workflow if final save config of switch fails = 0
 - Additional CLI commands:
clock time-zone Australia Sydney
ip dhcp-snooping enable

getWorkflowId() workflow 'Onboard VSP' in category 'Workflows' not found
Traceback (most recent call last):
  File "<string>", line 1538, in <module>
  File "<string>", line 1231, in main
  File "<string>", line 378, in exitError
RuntimeError: Serial-Number: Unable to locate workflow id for 'Workflows/Onboard VSP'

Traceback (most recent call last):
  File "<string>", line 1538, in <module>
  File "<string>", line 1231, in main
  File "<string>", line 378, in exitError
RuntimeError: Serial-Number: Unable to locate workflow id for 'Workflows/Onboard VSP'


I've also put in a screenshot of my workflows.

<img width="593" alt="image" src="https://github.com/extremenetworks/ExtremeScripting/assets/1151853/f1314bfc-501e-4af1-8503-25b494604502">

**Comment by jtrott** [comment]
Hi Ludovico.

Thanks for that clarification. Unfortunately I've run out of switches to test with on this project, I'll have to test this workflow again on our next Extreme ZTP+ project.
Regarding the strange serial and MAC, don't worry about that it was just me trying to sanitise the output.

Thanks,
JT

**Comment by jtrott** [comment]
Can confirm that the follow on workflow works as expected when using the Provisioning/Onboard VSP syntax.

**Comment by lgastevens** [comment]
Well yes, it works for me!
