### ISSUE TITLE
Make XIQ-SE licensing calculation into an Inventory Report

### ISSUE THREAD

**Issue by jtekjam** [extremenetworks/ExtremeScripting#194]
Is there a way to use this XIQ-SE licensing calculation workflow to create workflow that can be scheduled to send out the CSV as an inventory report? Is there a way to make it split out the universal switches just like it does the EXOS stacks? Currently it does not separate out that out and lists Universal Switch Stacks as "Universal Platform Switch Engine - Switch Engine ARM Stack" and does not break them out. 

Any help would be appreciated.

**Comment by Maranoj** [comment]
I suggest at modifying the ERS report workflow. It uses combination of NBI calls and commands sent the switches to compile the appropriate information.

**Comment by mnikulski** [comment]
Hi Josh,

not sure what you exactly looking for. In case it is an inventory of all the components and serials of the switch/stack?
If so, I do have one in my pocket which isn't published so far.
Markus Nikulski
Principal System Engineer / Extreme Networks
***@***.******@***.***>
Office  / +49 6947860419<tel:+49%206947860419>
ExtremeNetworks.com<https://extremenetworks.com/>
Advance with UsTM<https://extremenetworks.com/>

From: Josh ***@***.***>
Sent: Thursday, May 2, 2024 6:08 PM
To: extremenetworks/ExtremeScripting ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL][extremenetworks/ExtremeScripting] Make XIQ-SE licensing calculation into an Inventory Report (Issue #194)


Is there a way to use this XIQ-SE licensing calculation workflow to create workflow that can be scheduled to send out the CSV as an inventory report? Is there a way to make it split out the universal switches just like it does the EXOS stacks? Currently it does not separate out that out and lists Universal Switch Stacks as "Universal Platform Switch Engine - Switch Engine ARM Stack" and does not break them out.

Any help would be appreciated.

-

**Comment by jtekjam** [comment]
Thank you for the replies! I would be greatly interested in your inventory one. 

 I am looking for the similar or same CSV output from the XIQ SE licensing Workflow with each device listed with ip, nickName,sysName,deviceDisplayFamily,deviceDisplayType,serialNumber and firmware. License information isn't really needed. Just trying to automate an inventory list that breaks out the switch portion from their stacks and output to a CSV. 

Thank you for the help!

**Comment by jtekjam** [comment]
I will give it a try and report back - thank you!

**Comment by jtekjam** [comment]
This works great! 

I am going to tweak it a bit and see about adding variables for which columns to included to create different scheduled workflow tasks for different reports. 

Thank you again!

**Comment by mnikulski** [comment]
is published in the mean while

https://github.com/extremenetworks/ExtremeScripting/blob/master/XMC_XIQ-SE/oneview_workflows/xwf/Inventory_check-24.2.12.19v123.xwf
