### ISSUE TITLE
SCRIPT TO BACKUP EOS USING SCP PROTOCOL

### ISSUE THREAD

**Issue by JOSEBARO** [extremenetworks/ExtremeScripting#20]
Hi, 
We need a script to backup configuration of switch B5G124 FROM Inventory Manager using SCP protocol.

I hope you can help me!!

**Comment by dclaybrook** [comment]
Hi Jose,
This might be a question best suited for our customer community, [The Hub](https://community.extremenetworks.com/extreme).  Specifically in our [Scripting section](https://community.extremenetworks.com/extreme/categories/extreme_scripting).

You'll get more visibility there.
Thanks!

**Comment by stewilliams-extr** [comment]
Jose,

Thanks for posting this on Github.  We will see if we can get this working for you.

Thanks,

Stephen

**Comment by stewilliams-extr** [comment]
Jose,

It looks like you don't need a script for this.  In Inventory Manager just right click on the device and select file transfer method.  Select SCP.

Does that answer your question?
