### ISSUE TITLE
RuntimeError when trying to use script

### ISSUE THREAD

**Issue by mflammia** [extremenetworks/ExtremeScripting#27]
Hi,

Get the following error when trying to run the script, have put in some simple data in just to test:

run script snmpassist
Would you like to (D)elete or (C)onfigure SNMPv3? c
Please enter your SNMPv3 User name: netsight
Please enter your SNMPv3 User password (8 to 49 char): password01
Please enter your SNMPv3 privacy password (8 to 49 char): password01
Please enter your authentication type (SHA/MD5): SHA
Please enter your encryption type (3DES, AES, DES, HEX): AES

Traceback (most recent call last):
  File "/config/snmpassist.py", line 204, in <module>
    main()
  File "/config/snmpassist.py", line 119, in main
    (snmpuser, authtype, authpw, privpw, privtype))
RuntimeError

I have tried running the delete option which went fine.

Firmware version is 16.1.3.6-patch-1-11 on an X440-24p

**Comment by btclay** [comment]
@mflammia What does your config look like when you get this error? I was unable to reproduce this with the same EXOS version.
