### ISSUE TITLE
New script request - Auto Capture and Save Config File

### ISSUE THREAD

**Issue by Kingpa3017** [extremenetworks/ExtremeScripting#28]
I would like a script that will grab my current and future switch configuration files and copy them to a network path. 
I would like the script to run every time the config files change or update. I have many switches

**Comment by btclay** [comment]
@Kingpa3017 I think autofsbackup can be modified to do what you want.

https://github.com/extremenetworks/ExtremeScripting/tree/master/EXOS/CLI_Scripting/autofsbackup
