### ISSUE TITLE
Mlag check script 

### ISSUE THREAD

**Issue by andreas1o** [extremenetworks/ExtremeScripting#30]
I run this script on my switch and get the following
 run script mlag_config_check

>> Checking MLAG Configuration and Status...

>> Checking MLAG Peer "XITESEFYL0001-RD"...
>> CONFIG ERROR: Port 51, a LAG member of the ISC for peer XITESEFYL0001-RD, is down.  Please resolve.
>> CONFIG ERROR: MLAG port 7 for peer XITESEFYL0001-RD is down.  Please resolve.
>> CONFIG ERROR: MLAG port 8 for peer XITESEFYL0001-RD is down.  Please resolve.
>> CONFIG ERROR: VLAN None is found on an MLAG port but not added to ISC port 52
>> Would you like to add the missing vlans to the ISC? (y/n)y
Adding missing VLANS..

Traceback (most recent call last):
  File "/config/mlag_config_check.py", line 406, in <module>
    main()
  File "/config/mlag_config_check.py", line 374, in main
    clicmd('configure vlan {0} add port {1} tagged'.format(vlan, isc_port))
RuntimeError

I get the exact same message on both mlag peers. 

I know problems with port 7-8 ,51 But vlan NONE is not known to me.

Version on the script is the newest from github and 
Version on the switches is : ExtremeXOS version 22.2.1.5 22.2.1.5-patch1-4

**Comment by chadasmith** [comment]
This is a bug that needs to be resolved.  I believe it will occur when an MLAG port has no VLANs assigned. This would still be considered an MLAG configuration error, but should be handled correctly and be more descriptive.
