### ISSUE TITLE
Script Fails

### ISSUE THREAD

**Issue by thetechgy** [extremenetworks/ExtremeScripting#32]
Attempted to use this to configure SNMP on a stack of X440G2-48p-10G4's running EXOS 22.2.1.5 and it failed citing the error shown below

![image](https://user-images.githubusercontent.com/17523918/30997852-8a7c8c46-a498-11e7-831f-dee7904ef035.png)

**Comment by thetechgy** [comment]
Just noticed that this was reported in issue #27 as well

**Comment by stewilliams-extr** [comment]
Could you send us all the commands/input used to get to this error?

Thanks,

Stephen

**Comment by bparkerextr** [comment]
Are there any special characters in your auth/priv passwords?

**Comment by btclay** [comment]
Also, what is the current SNMP (before running the python script) config on this switch?
