### ISSUE TITLE
autofsbackup scripts are NOT OK

### ISSUE THREAD

**Issue by seurat-atreides** [extremenetworks/ExtremeScripting#33]
My guess is no one in the ExtremeNetworks/Extremescripting team tested the scripts contained in this folder.
It's frustrating having to debug scripts one assumes are OK because the have been published by ExtremeNetworks.
How can I contribute with corrected scripts?

**Comment by stewilliams-extr** [comment]
ExtremeNetworks/Extremescripting is an open source repository where Extreme and Non-Extreme employees contribute.  These scripts are not officially published or supported by ExtremeNetworks as stated in our disclaimers.  

We appreciate you letting us know about the problem in the script.  This was an older script we imported from another location.  We are happy to fix it, but if you already have a fix you can contribute by submitting a pull request.  We are always looking for community involvement, see the link below for ways to contribute.

https://gtacknowledge.extremenetworks.com/articles/How_To/How-do-I-post-a-script-on-Extreme-Networks-GitHub-page

Thanks,

Stephen
