### ISSUE TITLE
raw_input() -> input()

### ISSUE THREAD

**Issue by MidgetAteMyMom** [extremenetworks/ExtremeScripting#38]
The raw_input() method, used to get input for the name of the scriptfile (line 170) was renamed to input() in Python 3.0
this issue was found, today, in rmtscript.py

**Comment by stewilliams-extr** [comment]
This is not the only python2 dependency.  Added python2 to shebang and Readme file.

https://github.com/extremenetworks/ExtremeScripting/commit/b00936c79a8775412b9a1ce77235dd3def1879c0
