### ISSUE TITLE
New script request

### ISSUE THREAD

**Issue by wolfberg** [extremenetworks/ExtremeScripting#44]
I would like to have a script to backup the configuratio of Juniper Firewalls SRX 345 (junos-srxsme-18.1R2.5) in Extreme Management Center 8.1.4.40. 
File transfer over ssh/scp. 
Thanks a lot

**Comment by ZdenekPala** [comment]
I see how to save the config. Can you please share the same for "how to send the config to TFTP" destination?

Also how to recover = download the config and apply the config.

Thank you.

**Comment by wolfberg** [comment]
Hi 
Below the requested output. The transfer methode for the configuration is secure copy because tftp is not available. 
##################################
# scp (Juniper to EMC)           #
##################################

=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2018.09.17 15:21:57 =~=~=~=~=~=~=~=~=~=~=~=
login as: root

Password:
Last login: Mon Sep 17 15:12:38 2018 from 10.126.71.238

--- JUNOS 18.1R2.5 built 2018-05-25 20:43:01 UTC

root@srx345% scp backup_config_20180917_0901.cfg root@<destination IP>:<destination folder>

Password:
backup_config_20180917_0901.cfg                                                                         0%    0     0.0KB/s   --:-- ETA
backup_config_20180917_0901.cfg                                                                       100%   27KB  26.9KB/s   00:00    
root@srx345% 

##################################
# load (get config and load)     #
##################################

=~=~=~=~=~=~=~=~=~=~=~= PuTTY log 2018.09.17 16:17:15 =~=~=~=~=~=~=~=~=~=~=~=
login as: root


Using keyboard-interactive authentication.
Password:
Last login: Mon Sep 17 15:23:00 2018 from 10.126.71.238

--- JUNOS 18.1R2.5 built 2018-05-25 20:43:01 UTC



root@srx_345% 
root@srx_345% scp <EMC IP>:/<source directory>/backup_config_20180917_1539.cfg .


Password:


backup_config_20180917_1539.cfg                                                   100%   27KB  26.9KB/s   00:00    

root@srx_345%cli

root@srx_345> configure 
Entering configuration mode

[edit]
root@srx_345# load override backup_config_20180917_1539.cfg 
|/-load complete

[edit]
exit

**Comment by ZdenekPala** [comment]
Hi.

commands seems to be the same for Juniper EX series and for SRX Firewall.

I just uploaded SCP version for Juniper EX series. please try that and let me know

Thank you

Z.

**Comment by wolfberg** [comment]
Thank a lot its working fine.
