### ISSUE TITLE
Request - Backup Configs on Barracuda NG Firewall F-Series

### ISSUE THREAD

**Issue by byronmorales** [extremenetworks/ExtremeScripting#45]
Any help in getting Barracuda Firewall support into Netsight. Backup scripts, and deviceviews would be great.

**Comment by ZdenekPala** [comment]
Hi,

I can help with that. Unfortunately I do not have Barracuda NG firewall for testing. If you provide me with CLI output with commands sending the configuration to the TFTP destination then I can look at that.

The same for CLI output for TFTP download of the configuration and activating the configuration.

Regards

Z.

**Comment by byronmorales** [comment]
here's a backup script example they have on their support page. It Uses ftp to upload the PAR (backup file) to its destination. But it could probably be modified for tftp or scp.

```
#!/bin/bash
#########################
#echo "Backup-Script for Barracuda NextGen Firewall F-Series"
#echo "---------------------------------"
#echo "Creation of archive files"
#echo "ftp or scp -transfer onto 10.0.0.1"
#echo "---------------------------------"
HOST='10.0.0.1'
USER='yourusername'
PASSWD='yourpassword'
DSTPATH='/root/'
FILENAME1=CC-tree_`date +%Y_%m_%d_%H_%M`.par
FILENAME2=CC-box_`date +%Y_%m_%d_%H_%M`.par
cd /opt/phion/maintree/
/opt/phion/bin/phionar cdl /root/${FILENAME1} configroot/* history/*
cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/${FILENAME2} *
#########################
# Example of ftp:
cd /root/
ftp -n $HOST <<END_SCRIPT
quote USER $USER
quote PASS $PASSWD
cd $DSTPATH
binary
put ${FILENAME1}
put ${FILENAME2}
quit
END_SCRIPT
#########################
# Example of scp: Note: You have to exchange your keys with the destination!
/usr/bin/scp /root/${FILENAME1} $USER@$HOST:${DSTPATH}/${FILENAME1}
/usr/bin/scp /root/${FILENAME2} $USER@$HOST:${DSTPATH}/${FILENAME2}
#########################
# Garbage Collection
rm -f /root/${FILENAME1}
rm -f /root/${FILENAME2}
exit 0
```

Here's a link to Barracuda's Page 
https://campus.barracuda.com/product/cloudgenfirewall/doc/73719757/how-to-create-par-or-pca-files-on-the-command-line/

**Comment by byronmorales** [comment]
Hi Z,

Did you need any more info?

**Comment by ZdenekPala** [comment]
Hi.

as I do not know barracuda and what "phionar" command is doing (just guess). The first attempt is between hashes below. you may need to ssh to your barracuda and try the scp for first time as the scp may ask "trust the key" question.

######
-- Use this script to backup Barracuda firewall
name="Barracuda - scp"
desc="Barracuda SSH - SCP Script"
protocol=SCP
-- 
separator=UNIX_FILE_SEPARATOR
timed_reset_delay_format="HH:mm"
perform_success_test_always=false
-----BEGIN SCRIPT "Configuration Upload"-----
cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/%TARGET_FILE_NAME% *
/usr/bin/scp /root/%TARGET_FILE_NAME% %SCP_USER%@SCP_IP%:%ABSOLUTE_TARGET_FILE_PATH%
@receive 2 
%SCP_PSWD% 
@receive 30 
@COMMANDDONE 20
rm -f /root/%TARGET_FILE_NAME%
exit
-----END SCRIPT-----

-----BEGIN SCRIPT "Configuration Download"-----
-----END SCRIPT-----

-----BEGIN SUCCESS "Configuration Upload"-----
-----END SUCCESS-----
-----BEGIN SUCCESS "Configuration Download"-----
-----END SUCCESS-----
######

let me know what is the result = what is the log...

**Comment by ZdenekPala** [comment]
ok I hit the comment too early.. sorry. here is the code:

> -- Use this script to backup Barracuda firewall
name="Barracuda - scp"
desc="Barracuda SSH - SCP Script"
protocol=SCP
-- 
separator=UNIX_FILE_SEPARATOR
timed_reset_delay_format="HH:mm"
perform_success_test_always=false
-----BEGIN SCRIPT "Configuration Upload"-----
cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/%TARGET_FILE_NAME% *
/usr/bin/scp /root/%TARGET_FILE_NAME% %SCP_USER%@SCP_IP%:%ABSOLUTE_TARGET_FILE_PATH%
@receive 2 
%SCP_PSWD% 
@receive 30 
@COMMANDDONE 20
rm -f /root/%TARGET_FILE_NAME%
exit
-----END SCRIPT-----
-----BEGIN SCRIPT "Configuration Download"-----
-----END SCRIPT-----
-----BEGIN SUCCESS "Configuration Upload"-----
-----END SUCCESS-----
-----BEGIN SUCCESS "Configuration Download"-----
-----END SUCCESS-----

**Comment by byronmorales** [comment]
I'm getting a config file empty error in netsight

**Comment by ZdenekPala** [comment]
There should be more information in the log if you enable debug...

**Comment by byronmorales** [comment]
Do you know which debug option in netsight I need to enable?

![screenshot 2018-10-04 11 42 11](https://user-images.githubusercontent.com/8183269/46486028-e25f0780-c7ca-11e8-9f0e-21b16b05b0c3.png)

![screenshot 2018-10-04 11 42 42](https://user-images.githubusercontent.com/8183269/46486036-e68b2500-c7ca-11e8-9592-d86fd75f83f9.png)

**Comment by ZdenekPala** [comment]
there are two: Inventory Manager, Inventory Manager - script. Configure those two.

**Comment by byronmorales** [comment]
[server.log](https://github.com/extremenetworks/ExtremeScripting/files/2447117/server.log)

**Comment by ZdenekPala** [comment]
try this:

```-- Use this script to backup Barracuda firewall
name="Barracuda - scp"
desc="Barracuda SSH - SCP Script"
protocol=SCP
-- 
separator=UNIX_FILE_SEPARATOR
timed_reset_delay_format="HH:mm"
perform_success_test_always=false
-----BEGIN SCRIPT "Configuration Upload"-----
cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/%TARGET_FILE_NAME% *
/usr/bin/scp /root/%TARGET_FILE_NAME% %SCP_USER%@%SCP_IP%:%ABSOLUTE_TARGET_FILE_PATH%
@receive 2 
%SCP_PSWD% 
@receive 30 
@COMMANDDONE 20
rm -f /root/%TARGET_FILE_NAME%
exit 0
-----END SCRIPT-----
-----BEGIN SCRIPT "Configuration Download"-----
-----END SCRIPT-----
-----BEGIN SUCCESS "Configuration Upload"-----
-----END SUCCESS-----
-----BEGIN SUCCESS "Configuration Download"-----
-----END SUCCESS-----```

I suggest you delete the server.log post as password is there in clear text.

**Comment by byronmorales** [comment]
This is what I get now

[log2.log](https://github.com/extremenetworks/ExtremeScripting/files/2447509/log2.log)

**Comment by ZdenekPala** [comment]
![image](https://user-images.githubusercontent.com/16311452/46495623-3511e100-c816-11e8-8f10-721980638c8c.png)
do you have your SCP credentials configured for your X.X.175.33?

**Comment by ZdenekPala** [comment]
the log says the scp password is not correct.
another option is you have space behind %SCP_PSWD%

**Comment by byronmorales** [comment]
Awesome! I removed the empty space after %SCP_PSWD% and it worked!
Is there a way to have the file extension be .par instead of .cfg?

**Comment by ZdenekPala** [comment]
AFAIK the answer is no. I can change the name, but then XMC will not find the file => it will not work.

In the mentioned web the procedure is to create one file (as my script does). Original script you shared include more files to be part of backup.

Can you confirm all necessary information is included in the backup?

Is there procedure for configuration recovery?

**Comment by byronmorales** [comment]
Ok. Its easy enough to manually change the extension after I download it from netsight.
The other file in the script I sent isn't actually a config and backs up logs I believe. 

Running cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/%TARGET_FILE_NAME% * is what is needed to get the config settings.

The file created is in binary so I can't run a diff and compare it that way to the one that is created in netsight. But just opening the file in terminal it is mostly legible and it looks like the one that you get when you manually create the backup from the firewall.

I'll see if i can get my hands on a test box. I only have a production firewall at the moment.

Below is the procedure to do a restore via the command line.

`Emergency Restore via SSH
If you can reach your Barracuda CloudGen Firewall via SSH, you can also perform an emergency restore via SSH.

If necessary, rename the PCA or PAR file to box.par or box.pca.
Copy the box.par or box.pca file to the /opt/phion/update/ directory on the Barracuda CloudGen Firewall.
If you are restoring the configuration with a PCA file created with the -P option, or the serial number used as the password of the PCA file does not match the appliance, decrypt the file using the following command:

 phionar D -P YOURPASSWORD myarchive.pca myarchive.par 
Restart the phion service to initiate the emergency restore:

/etc/rc.d/init.d/phion stop
/etc/rc.d/init.d/phion start`

**Comment by ZdenekPala** [comment]
this might work for configuration restore also:

```
name="Barracuda - scp"
desc="Barracuda SSH - SCP Script"
protocol=SCP
-- 
separator=UNIX_FILE_SEPARATOR
timed_reset_delay_format="HH:mm"
perform_success_test_always=false
-----BEGIN SCRIPT "Configuration Upload"-----
cd /opt/phion/config/configroot/
/opt/phion/bin/phionar cdl /root/%TARGET_FILE_NAME% *
/usr/bin/scp /root/%TARGET_FILE_NAME% %SCP_USER%@%SCP_IP%:%ABSOLUTE_TARGET_FILE_PATH%
@receive 2
%SCP_PSWD%
@receive 30
@COMMANDDONE 20
rm -f /root/%TARGET_FILE_NAME%
exit 0
-----END SCRIPT-----
-----BEGIN SCRIPT "Configuration Download"-----
/usr/bin/scp %SCP_USER%@%SCP_IP%:%ABSOLUTE_TARGET_FILE_PATH% /opt/phion/update/%TARGET_FILE_NAME%
@receive 2
%SCP_PSWD%
@receive 30
@COMMANDDONE 20
rm -f /opt/phion/update/box.par
mv /opt/phion/update/%TARGET_FILE_NAME% /opt/phion/update/box.par
/etc/rc.d/init.d/phion stop
/etc/rc.d/init.d/phion start
@receive 30
@COMMANDDONE 20
exit 0
-----END SCRIPT-----
-----BEGIN SUCCESS "Configuration Upload"-----
-----END SUCCESS-----
-----BEGIN SUCCESS "Configuration Download"-----
-----END SUCCESS-----
```

**Comment by SushNep** [comment]
![image](https://user-images.githubusercontent.com/86577298/227400805-0b2d99c3-67c7-4cdf-8dde-95ac3caf159b.png)
![image](https://user-images.githubusercontent.com/86577298/227400929-413f02c5-cc74-4a68-bb49-618144ac6783.png)
Script throws up an error "Access denied: 534". any idea on how to fix it. Sorry, I am newbie in Bash scripting and Linux
