### ISSUE TITLE
Pull config backup from device via SCP

### ISSUE THREAD

**Issue by chrwurm** [extremenetworks/ExtremeScripting#46]
Hi there,

I wanted to ask whether we could have a script that pulls the config of a device via SCP from the device to XMC. Usually it is the other way round: XMC logs in on a device via SSH and pushes the config to the XMC server. I want to have it the other way round.

Reason: I monitor Fortigate Firewalls via XMC which are connected via VPN. However when opening a SSH session on these Fortigates and pushing the config via TFTP/SCP it can upload the file because it fails to properly set the source IP for the config backup - this is a common issue, see https://forum.fortinet.com/tm.aspx?m=145589

To avoid this I would like to pull the config. Is this possible and if yes: how should the XMC backup script look like?

Thank you very much in advance!

Kind regards
Christian

**Comment by ZdenekPala** [comment]
Hi,

it will not be easy without real "dirty" scripting in the operating system. the XMC does not care what IP does upload required config = if you manage to upload it from any other IP address (different IP on the fortigate) it will work.

Z.
