### ISSUE TITLE
new python script for ISW-configuration backup

### ISSUE THREAD

**Issue by jakirhussainp7** [extremenetworks/ExtremeScripting#50]
Hi team,
I was looking for script to take configuration backup on ISW switches over 300 running on SSH. Provide me the solution for this on python script.

**Comment by ZdenekPala** [comment]
Our product Extreme Management Center does have this feature build in.
https://www.extremenetworks.com/product/extreme-management-center/

**Comment by jakirhussainp7** [comment]
> 
> 
> Our product Extreme Management Center does have this feature build in. This feature is included also in the Base license package.
> https://www.extremenetworks.com/product/extreme-management-center/

Is Extreme management control center software is available for free or any price?
We have observed it has flavors like (Extreme Analytics, Extreme Contol, Extreme Fabric mgr, Extreme Management), which one is reach our requirement.

**Comment by ZdenekPala** [comment]
The Extreme Management Center is a commercial product (not for free). You can get an evaluation license (time-limited, feature unlimited, capacity unlimited).
The ExtremeControl and ExtremeAnalytics both are "extension" of Extreme Management Center. 
If you chose ExtremeControl (perpetual license) then you get Extreme Management Center included. 
If you chose ExtremeAnalytics (perpetual license) then you get Extreme Management Center included.
Fabric Manager (visualization) is part of Base license also.

**Comment by jakirhussainp7** [comment]
Hi Pala,
Thanks for  the valuable info.
We've installed EMC with evaluation license. Please guide us how to login with default username&password.
