### ISSUE TITLE
Doesn't work for any/any rows 

### ISSUE THREAD

**Issue by padeniso** [extremenetworks/ExtremeScripting#54]
Hi,

The script refused to convert the following rows in the IOS ACL:
permit ip host 172.16.183.2 172.16.248.0/27 any any 
permit ip host 172.16.183.3 172.16.248.0/27 any any 
permit ip host 172.16.183.2 172.16.253.128/28 any any 
permit ip host 172.16.183.3 172.16.253.128/28 any any 
permit ip host 172.16.183.2 172.24.11.128/28 any any 
permit ip host 172.16.183.3 172.24.11.128/28 any any 
permit ip host 172.16.183.2 172.16.153.1/24 any any 
permit ip host 172.16.183.3 172.16.153.1/24 any any

**Comment by ZdenekPala** [comment]
Hi Pavel.

please be more specific. What script?

Thx.

**Comment by stewilliams-extr** [comment]
@ZdenekPala I think they are talking about the IOStoEXOSACL Perl script for EXOS.

If you remove any any the script and use the revers mask instead of the slash it should work.
