### ISSUE TITLE
Gather Show Support Workflow Failing

### ISSUE THREAD

**Issue by byronmorales** [extremenetworks/ExtremeScripting#56]
Hi,

I downloaded and imported the "Gather Show Support" workflow and attached it to an alarm to run whenever a device CPU is high.

The alarm triggered on a switch but the workflow failed with the following message.

`Script Name: Gather Show Support_Prepare
Date and Time: 2019-11-20T00:03:33.512
XMC User: NetSight Server
XMC User Domain: 
IP: 10.44.100.100
Traceback (most recent call last):
  File "<string>", line 21, in <module>
TypeError: 'NoneType' object is unsubscriptable

Traceback (most recent call last):
  File "<string>", line 21, in <module>
TypeError: 'NoneType' object is unsubscriptable`

**Comment by ZdenekPala** [comment]
It seems the device that triggered the alarm is not in the XMC database...
I will investigate more.

**Comment by ZdenekPala** [comment]
Let me know if new version is better.

**Comment by byronmorales** [comment]
Ok. I downloaded the updated workflow and attached it the high cpu alarm. But just to be clear, this workflow can gather the show tech-support log from a x460-g2 switch right? Or is this just the show support log from XMC itself?

**Comment by ZdenekPala** [comment]
The workflow does gather the show tech-support from:
- Wireless Controller
- VSP
- Summit Series
- Catalyst
Based on the platform the transfer method is used (SCP or TFTP) and the file is stored in the XMC.
The next version of the workflow will send the tech-support file in the email attachment.

Z.

**Comment by ZdenekPala** [comment]
Please test the published one. version 16

**Comment by byronmorales** [comment]
I downloaded the latest published version 8.4.0.103v17.xwf and imported to XMC.
The High CPU alarm hasn't triggered so I'm tried running the workflow manually by adding it to the "Device" menu.

But when I run the task I get an error no compatible devices and the output comes up blank

**Comment by ZdenekPala** [comment]
I suggest having an online session to investigate. Does Wednesday 27th work for you?
What is your timezone? I am in central europe.
please reach me on zpala@...

Thx.

**Comment by byronmorales** [comment]
Hi,

I'm in Eastern Time Zone in the US. Looks like we are about 6 hours apart.

Today is probably going to be a short day with Thanksgiving holiday
tomorrow.

Can you do Monday Dec 2 between 10am-5pm Eastern Standard Time?

**Comment by ZdenekPala** [comment]
Hi.

I can offer Tuesday, Dec 3rd from 8 am - 10 am (EST) and Wednesday, Dec 4th from 8 am - 10 am (EST)

Does it fit?

**Comment by byronmorales** [comment]
I get to the office at 930am if that works for you tomorrow still.

**Comment by ZdenekPala** [comment]
9:30 till 10:00 am EST works for me.

**Comment by ZdenekPala** [comment]
Join Zoom Meeting
https://extremenetworks.zoom.us/j/9067500566

Meeting ID: 906 750 0566

One tap mobile
+16465588656,,9067500566# US (New York)

**Comment by byronmorales** [comment]
ok sounds good.

**Comment by ZdenekPala** [comment]
Workflow updated to handle the use-case. just modify the menu to allow right click.

**Comment by byronmorales** [comment]
Hi Z,

Looks like the file that is sent in the email has an issue. I can't
un-compress it.

[image: Screenshot 2019-12-04 10.38.53.png]

I attached the file to see if you have the same issue.

**Comment by ZdenekPala** [comment]
That is the way how EXOS does generate the tech support. GTAC can uncompress it.
The workflow is not doing compression.

Let me check with GTAC how they decompress the file
Z.

**Comment by bparkerextr** [comment]
I normally use WinRar or 7-zip to open the .tgz file.

**Comment by byronmorales** [comment]
Looks like the show tech log that is being created on the switch is corrupt, its not the workflow or email. I copied the show tech log directly from the switch and I still can't uncompress them. But if I try it from another switch it works fine.

This switch is intermittently under load so maybe having it try to generate a show support at that time is pushing it over the edge. 

The last 3 High CPU Alarms today with the gather show support workflow attached didnt even attach the file because of a timeout, even though they are on the switch

![Screenshot 2019-12-05 13 37 48](https://user-images.githubusercontent.com/8183269/70263476-71b3d200-1764-11ea-8530-580fb5d04fff.png)

**Comment by ZdenekPala** [comment]
This issue is reported to GTAC and it is documented here:
- Case: (01961145)
- https://gtacknowledge.extremenetworks.com/articles/Solution/Running-show-tech-support-all-detail-logto-file-generates-a-corrupt-file
