### ISSUE TITLE
HPE H3C Comware script does not work with H3C 7.1

### ISSUE THREAD

**Issue by FlavioB79** [extremenetworks/ExtremeScripting#75]
Hi all.
I've tried using the script with H3C running firmware 7.1 and it won't work.
XMC tells me "Backup failed, TFTP error".
I'm running XMC 8.3.3.11

Any help?
Thanks,
Flavio.

**Comment by ZdenekPala** [comment]
Hi Flavio.

can you share the CLI?
- commands you use to backup configuration from your switch to TFTP server
- what is the CLI output if the TFTP transfer is successful

Z.

**Comment by FlavioB79** [comment]
Hi Zdenek.
I tested it as follows. I open "Terminal" from XMC GUI and after logging in, I type:

<NV0014>backup startup-configuration to 10.114.4.227 NV0014.cfg
Backup next startup-configuration file to 10.114.4.227,please wait...
Backup failed, TFTP error!

Trying to TFTP to another server (Jounin's TFTP Server), it looks like this:
<NV0014>backup startup-configuration to 10.114.4.40 NV0014.cfg
Backup next startup-configuration file to 10.114.4.40,please wait...
Finished.

Thanks for your help!
Flavio.

**Comment by ZdenekPala** [comment]
Hi Flavio.

Please try this, and let me know.
- upload the file to your XMC
- change your XMC to use the new file with your H3C
- try configuration backup

[HPE_H3C_Comware_7_Switch.txt](https://github.com/extremenetworks/ExtremeScripting/files/4408619/HPE_H3C_Comware_7_Switch.txt)

**Comment by FlavioB79** [comment]
Hi Zdenek - IT WORKS! What did you actually change? At first look, I couldn't see the difference between the 5 and the 7 version scripts...
F.

**Comment by ZdenekPala** [comment]
That is a secret sauce 👯‍♂ 
the H3C changed the response if it is sucessful from "finished!" to "Finished."
I will publish this file to GitHub.
thanks for cooperation!

**Comment by FlavioB79** [comment]
Yeah - that's the only difference I noticed, so I actually ignored it :-(
Thanks for your quick help!

I still got an issue that XMC is not backing up some HP5900AF switches running the same Comware version 7.1.045 as the other switches (HPE 5130 - the ones now "fixed").

Any further help here?
Thanks,
Flavio.

**Comment by ZdenekPala** [comment]
Lets repeat the procedure:
What commands you use and what is the switch response?

**Comment by FlavioB79** [comment]
Sorry - this time it was a firewall issue: I missed that there was no policy for the "core" switches...
All good!
Thanks again!
Flavio.
