### ISSUE TITLE
Fortinet (FortiWeb, FortiMail, FortiSandbox) backup script?

### ISSUE THREAD

**Issue by FlavioB79** [extremenetworks/ExtremeScripting#76]
Hi all.
I tried to use the Fortigate script on the mentioned Fortinet devices (FWB, FML, FSA) without success.
For FML and FSA, GTAC told me that the issue lies in the fact that XMC fails because the two end-devices do not support SSH password-mode.
Has anybody successfully backed up the units I mentioned in some other way?
Thanks,
Flavio.

**Comment by ZdenekPala** [comment]
The XMC can backup the config if it is invoked by SSH or telnet. If the SSH is not supported then we can not.

You mentioned SSH password mode, do these devices support key-based authentication?
