### ISSUE TITLE
SLX Event Handler Scripts try to log to an unwritable location

### ISSUE THREAD

**Issue by crami** [extremenetworks/ExtremeScripting#89]
All the event handler scripts try to writhe to the same directory as the script is located (/var/config/vcs/scripts/), which is not writable by the user that runs the event handler. The following execption is thrown on registration:

```
SLX1# python po_member.py -r
Traceback (most recent call last):
  File "po_member.py", line 1127, in <module>
    main()
  File "po_member.py", line 1113, in main
    datefmt='%Y-%m-%dT%H:%M:%S%z')
  File "/usr/lib/python3.5/logging/__init__.py", line 1750, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.5/logging/__init__.py", line 1014, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.5/logging/__init__.py", line 1043, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/config/vcs/scripts/po_member.log'
```

I changed the line which defins the logifile to this to fix it. But probably there is a better solution.
```
    log_filename = "/tmp/" + sys.argv[0].split('/')[-1].split('.')[0] + '.log
```

SLX is Running SLX-OS 20.2.2b

**Comment by mayafox** [comment]
Matthias, 
Sorry for the late response.
I suspect the access to /var/config/vcs/scripts/ (the contents of which are shown by the 'dir' command) became inaccessible when running python from the SLXOS cli was changed to run python as a non-privileged user (security fix). 

/tmp does work, but it's not the prettiest or best solution from an end-user standpoint and should be addressed on the SLXOS side in my opinion. 
Would you be willing to contact Extreme support for this issue?
