### ISSUE TITLE
Barracuda-SCP.txt Stopped working.

### ISSUE THREAD

**Issue by byronmorales** [extremenetworks/ExtremeScripting#91]
Hi,

How can I enable debugging for this script in netsight?

I'm using netsight 8.5.2.6.

I'm not exactly sure when this script stopped working. I have other locations were netsight is on version 8.3.x. 

Also the firewall firmwares are can range from 7.2.6-8.0.x.

I thought it might have been an ssh issue since from the netsight command line I would get a "their offer ssh-dss" when i tried to ssh to the firewall. I added a ssh config file which fixed the error but i'm not sure if the daemon that runs the backup script uses the config file.

Any help would be appreciated.

**Comment by ZdenekPala** [comment]
OneView -> Administration -> Diagnostics -> Level: Diagnostics -> Server -> Server Diagnostics -> Inventory Manager Script
![image](https://user-images.githubusercontent.com/16311452/110158605-e18e8d80-7de9-11eb-84ce-09423eb42373.png)
